### ISSUE TITLE
Error when other plugins manage windows.

### ISSUE THREAD

**Issue by jordwalke** [zefei/vim-wintabs#13]
I saw the following error multiple times - when using `ctrl-p` and closing the ctrlp window via `ctrl-c`. Do you have any ideas?

<img width="1022" alt="screen shot 2017-02-19 at 1 22 59 am" src="https://cloud.githubusercontent.com/assets/977348/23101116/1b690f6e-f642-11e6-8b2e-1f99725b1e56.png">

**Comment by zefei** [comment]
It seems that wintabs is accessing a window that no longer exists, which results in this NPE. I just landed a possible fix (fixing the NPE) but not sure if it fixes the actual problem, can you try it?

**Comment by jordwalke** [comment]
I *think* this might have fixed it! Thank you.
