### ISSUE TITLE
WintabsClose doesn't delete buffers

### ISSUE THREAD

**Issue by fatalis** [zefei/vim-wintabs#17]
Is there a reason why? The docs claim that this is a replacement for :bd but it only disassociates them with the tab. If you're using session management you will end up having lots of zombie buffers.

**Comment by zefei** [comment]
I probably didn't do a good job on the docs. WintabsClose doesn't really delete buffers as that will cause all other windows that are showing this buffer to close. :bd technically doesn't delete buffer either, it just unlists the buffer (:bw actually deletes the buffer). So WintabsClose does similar thing to :bd as it unlists the buffer from tabs.

The zombie buffers is a real issue, I'll try to find a way to fix this. Though deleting a buffer without destroying windows is quite tricky in vim.

**Comment by zefei** [comment]
@fatalis I just pushed a fix for this issue, can you confirm if it's fixed?

**Comment by fatalis** [comment]
Yup, appears to be fixed, thanks!
