### ISSUE TITLE
g:wintabs_ui_active_left Not applied to first tab

### ISSUE THREAD

**Issue by jordwalke** [zefei/vim-wintabs#26]
I believe the first wintab doesn't show the active_left character:

```
let g:wintabs_display='statusline'
set hidden
let g:wintabs_autoclose=2
let g:wintabs_autoclose_vim=1
let g:wintabs_autoclose_vimtab=1
let g:wintabs_switchbuf='useopen,usetab'
let g:wintabs_ui_active_higroup = 'TabLineSel'



" If doing some custom rendered GUI use a not-actually space.
" let intertabSpace= ' '
let intertabSpace= ' '
let activeWinTabChar = '|'
" This must be different to distinguish.
let activeVimTabChar = '|'
let activeWinTabChar = '▎'
" This must be different to distinguish.
let activeVimTabChar = '▍'
let g:wintabs_ui_sep_leftmost=intertabSpace
let g:wintabs_ui_sep_inbetween=intertabSpace
let g:wintabs_ui_active_right=intertabSpace
let g:wintabs_ui_active_left=activeVimTabChar 
let g:wintabs_ui_sep_rightmost=intertabSpace
let g:wintabs_ui_modified=' ◎'
let g:wintabs_ignored_filetypes=[]
" Annotating the active vimtab makes it always available for detection
let g:wintabs_ui_active_vimtab_left=activeVimTabChar
let g:wintabs_ui_active_vimtab_right=intertabSpace

let g:wintabs_ui_arrow_left='«'
let g:wintabs_ui_arrow_right='»'

```

**Comment by zefei** [comment]
Not sure if this is one of the old design flaws that I now treat as a "feature". I rewrote some of the rendering steps to support unicode and custom rendering, which might be able to fix it. I haven't documented the changes yet, but you can take a look at https://github.com/zefei/vim-wintabs-powerline and see if that can help.

**Comment by jordwalke** [comment]
I see one can define their own custom renderer now. Nice.

**Comment by jordwalke** [comment]
Created a pull request in case you feel like it's worth merging: https://github.com/zefei/vim-wintabs/pull/28
Here's how I'm using it: To create the appearance of an IDE "currently selected tab" UI:

Without my PR, the blue selected line doesn't show up on the leftmost tab when active.
<img width="875" alt="screen shot 2018-02-09 at 12 38 15 am" src="https://user-images.githubusercontent.com/977348/36018696-911bcf42-0d31-11e8-940c-075820f9423e.png">

**Comment by zefei** [comment]
Manually merged.
