### ISSUE TITLE
Double error when closing with unsaved changes.

### ISSUE THREAD

**Issue by jordwalke** [zefei/vim-wintabs#27]
When you close a wintab that has not saved its changes, you'd expect to get an error (from Vim) but you get a double error which causes you to have to press enter with wintab.

<img width="758" alt="screen shot 2018-02-05 at 11 21 06 pm" src="https://user-images.githubusercontent.com/977348/35846410-69c16adc-0acb-11e8-8fe1-0ad2da1c791c.png">

**Comment by jordwalke** [comment]
I think it might be able to catch `E89` and just rethrow it up.

**Comment by zefei** [comment]
Not sure if the fix of #24 resolves this issue. For exception E89: vim can catch that but unfortunately (re)throwing vim exceptions isn't allowed.

Let me know if this is still an issue after the other error is fixed.

**Comment by zefei** [comment]
Should be fixed now.
