### ISSUE TITLE
Can't undo after changing tab

### ISSUE THREAD

**Issue by shuLhan** [zefei/vim-wintabs#3]
Lets say I have two tab, A and B.

If I save buffer in tab A, and change to tab B, and switch back to tab A, I can't undo what I has edit before in tab A.

Vim will say "Already at oldest change".

**Comment by noscript** [comment]
Somehow I cannot get rid of the issue without patching `wintabs`, even with `:set hidden`. What am I doing wrong?

Dirty workaround: 

```diff
--- a/autoload/wintabs.vim
+++ b/autoload/wintabs.vim
@@ -382,7 +382,7 @@ function! s:switch_tab(n, confirm)
 
   " set nohidden to trigger confirm behavior
   let hidden = &hidden
-  let &hidden = 0
+  "let &hidden = 0
 
   if a:n < 0
     execute a:confirm ? 'silent! confirm enew' : 'enew!'
```

**Comment by noscript** [comment]
Ok, apparently I needed both `:set undofile` and `:set hidden` to make it work.
