### ISSUE TITLE
Add a way to integrate with vim-airline

### ISSUE THREAD

**Issue by dylan-chong** [zefei/vim-wintabs#36]
Currently this plug-in overrides the status line (when using the status line option) 

it would be nice if there was a way to show the tabs in the status line, without overwriting the status line. For example by doing something like

    let g:airline_section_x = whatever_needs_to_be_here_to show all of the buffers

**Comment by zefei** [comment]
Support for vim-airline is already included: if you load vim-wintabs after vim-airline and choose to show wintabs on statusline, airline will be show on tabline. Let me know if that doesn't work for you.

**Comment by dylan-chong** [comment]
Ah yes, never mind, ignore me. I'm not sure what i was thinking when i reported this issue
