### ISSUE TITLE
Error when closing tab with unsaved changes

### ISSUE THREAD

**Issue by dylan-chong** [zefei/vim-wintabs#41]
How to replicate:

0. Configure vimrc
```
let g:wintabs_autoclose_vim = 1
let g:wintabs_autoclose_vimtab = 1
let g:wintabs_autoclose = 2
```
1. run `vim`
2. Type `:tabedit`
3. Insert some text and go back to normal mode
4. type  `call wintabs#close() `
5. Do not save changes to 'Untitled'
6. See the error below

<img width="498" alt="screen shot 2018-07-17 at 9 49 30 am" src="https://user-images.githubusercontent.com/17482349/42785544-0982261a-89a7-11e8-8783-8bb3eaa282ee.png">

**Comment by zefei** [comment]
Thanks for the repro and vimrc! Will try to fix this very soon.

**Comment by zefei** [comment]
This should be fixed in the last commit.
