### ISSUE TITLE
Tabs/buffers are not restored on session load

### ISSUE THREAD

**Issue by dylan-chong** [zefei/vim-wintabs#42]
Replication:

1. Open vim with a session, and file A
2. Open another buffer for file B
3. Save the session and  wqa
4. Reopen vim with the session. File B is restored but not file A

**Comment by zefei** [comment]
Hey, thanks for the report and repro. However I can't repro it with minimal settings. For this issue, I'd really need a minimal vimrc and more detailed repro steps (actual ex-commands), because I suspect it has something to do with other plugins.

**Comment by dylan-chong** [comment]
Hey thanks for trying to replicate it. I suspect that one extra step I didn't mention was that vim must be opened in the ~ directory, but I will try and find a minimal rc to replicate it sometime.

**Comment by dylan-chong** [comment]
Hello again, I have done some thorough testing and I have come to the conclusion that the issue must have been caused by some strange corruption issue with my Session.vim file. The problem seems to have gone away if I delete the old session file and create a new one, manually opening up all of my old files.
