### ISSUE TITLE
It's better if wintabs have go option

### ISSUE THREAD

**Issue by wanchaol** [zefei/vim-wintabs#45]
if wintabs have something similar to bufferline(https://github.com/mgee/lightline-bufferline#mappings), which can goes to specific tab with a single command, that would be awesome!

**Comment by zefei** [comment]
It has, please see the help text for `WintabsGo`. You can make your own mappings like the pre-defined ones here https://github.com/zefei/vim-wintabs/blob/master/plugin/wintabs.vim#L17-L27

**Comment by wanchaol** [comment]
Gotcha, thanks for sharing it, pretty awesome. I wondered if it also can have numbers appears together for the buffer in tabline? it's gonna be hard to know which number I jump to if it don't have a number along with the buffer.

**Comment by zefei** [comment]
@wanchaol currently this cannot be done without breaking some backward compatibility for renderers. You can try this PR to see if it works for you though https://github.com/zefei/vim-wintabs/pull/29/files.
