### ISSUE TITLE
Request: Ability to click on statusline buffers

### ISSUE THREAD

**Issue by eternauta1337** [zefei/vim-wintabs#52]
It would be awesome if I could click on a buffer item in the statusline of a window and have that window switch to that buffer. Is this possible? I imagine it would be if there is a way to make an area within the statusline clickable and associate some function to the mouse event.

**Comment by zefei** [comment]
@ajsantander wintabs supports click on tabline on neovim because neovim provides such API. There's no click API on statusline so this isn't possible from plugin. I'd happy to implement such API if we can add such  API to vim/neovim.
