### ISSUE TITLE
Format option for displaying vim tabs with separator

### ISSUE THREAD

**Issue by echuraev** [zefei/vim-wintabs#8]
You can set option `g:wintabs_ui_show_vimtab_name` equal 2. Then vim tabs will be displayed in this way: *<tab_number>:<tab_name>*. User is not able to customize the separator between number and name. 

We had a discussion with Zefei (@zefei) how it should be implemented in pull request #7. All discussion you can read [here](https://github.com/zefei/vim-wintabs/pull/7/files/56c726427b6d24db9a35a281b353b3a9f77ad4af#diff-c3176c06e0dd27d93aa4dc90dbe059f0).

The summary of this discussion is:
*"A good way to make format option for displaying vim tabs would be to allow user to free form the tab name like "%d: %n"."*

**Comment by echuraev** [comment]
@zefei Could you please create a label for this issue to mark it that it is not an issue but it is a feature request?

**Comment by zefei** [comment]
It would be nice to have this option to format both buffer tabs and vim tabs however the user wants.

**Comment by zefei** [comment]
Thank you for the patch, closing this issue.
