### ISSUE TITLE
Error "E444: Cannot close last window." when trying to close last window.

### ISSUE THREAD

**Issue by jordwalke** [zefei/vim-wintabs#9]
When I try to close the last window using `:WintabsClose`, I get the mentioned error. I would like it to close vim entirely when I run `:WintabsClose` on the final window/buffer.

No configuration of `|g:wintabs_autoclose|` or `*g:wintabs_autoclose_vimtab*` make this work.

I am testing in MacVim.

**Comment by zefei** [comment]
I'll fix this.

Meanwhile I'd suggest close vim using ZZ or ZQ, as they work very well with session and vimtabs (you can restore last session with all buffers re-opened if you quit with ZZ/ZQ).

**Comment by jordwalke** [comment]
@zefei As a user, I just want to be able to hit my keyboard shortcut for "close the thing", and have it close my buffers (wintabs actually), and then when I've finally closed all of them, that same command should close out of the final window, which quits Vim. This is how most applications that I use function (such as Chrome for example).

**Comment by jordwalke** [comment]
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=41231139)](https://www.bountysource.com/issues/41231139-error-e444-cannot-close-last-window-when-trying-to-close-last-window?utm_source=41231139&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by jordwalke** [comment]
@zefei Do you know of any way to do everything just as wintabs currently does it, but then have it automatically use `:q` for the final close? Is there a way to programmatically check how many wintabs remain assigned to the current window? I can create a custom key mapping that checks if I am the last window open, and then if I am *also* the last wintabs buffer assigned to this window, I would then have the keymapping call `:q` instead of `WinTabsClose`. I do feel like this should be the default behavior, but I'm definitely willing to create my own mapping that does it, if you are aware of a way to do this.

**Comment by zefei** [comment]
I didn't have much time last week, I'll probably fix it this weekend as this is just a one line fix. If you really want to do it now, you can do `try | WintabClose | catch | quit | endtry`.

**Comment by jordwalke** [comment]
Thanks for the suggestion. 
<img width="496" alt="screen shot 2017-01-27 at 11 06 30 pm" src="https://cloud.githubusercontent.com/assets/977348/22395004/4905c282-e4e5-11e6-9f9e-9c3e9a4f117c.png">

It seems this results in an error.

**Comment by zefei** [comment]
I added option `g:wintabs_autoclose_vim`, closing this.

**Comment by jordwalke** [comment]
Thanks so much!
